main-menu,Main Menu,Main Menu,1,0
<front>,Algemeen,2,0
    <front>,Club,20,2
        <front>,Geschiedenis,200,20
        <front>,Bestuur,201,20
        <front>,Lid worden,202,20
    <front>,Records,21,2
        <front>,Behaalde Titels,210,21
        <front>,Records Binnen,211,21
        <front>,Internationale Meeting,212,21
<front>,Athletiek,3,0
    <front>,Trainingen,30,3
        <front>,Openingsuren,300,30
        <front>,Trainers,301,30
    <front>,Wedstrijden,31,3
        <front>,AAS,310,31
        <front>,Nog een wedstrijd,311,31
<front>,Jeugd,4,0
    <front>,Trainingen,40,4
    <front>,Wedstrijden,41,4
<front>,Joggers,5,0
    <front>,Trainingen,50,5
        <front>,Parcours,500,50
        <front>,Trainers,501,50
    <front>,Start to Run,51,5
        <front>,Loopschema,510,51
        <front>,Inschrijven,511,51
